{% set name = "azure-uamqp-c" %}
{% set version = "2020.12.09" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/Azure/azure-uamqp-c/archive/2020-12-09.tar.gz
    sha256: 1db964ba4d771434be026194c3a7650d668637b94d75ebb68d911865a1a757bd

build:
  number: 0
  skip: true  # [not win]
  run_exports:
    - {{ pin_subpackage(name, exact=True) }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - azure-c-shared-utility
  run:
    - azure-c-shared-utility

test:
  commands:
    - if not exist %PREFIX%\\Library\\bin\\uamqp.dll exit 1  # [win]

about:
  home: https://github.com/Azure/azure-uamqp-c
  license: MIT
  license_file: LICENSE
  summary: |
    uAMQP is a general purpose C library for AMQP 1.0.

extra:
  recipe-maintainers:
    - xylar
    - seanyen
