schema_version: 1

context:
  name: azure-uamqp-c
  version: "2019.12.09"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://github.com/Azure/azure-uamqp-c/archive/LTS_02_2020_Ref01.tar.gz
    sha256: 8920d1ff729d6cc9c03b6b6d5d57490d8ab06aeca16279a6f3f940287601c9b3
    file_name: ${{ name }}-${{ version }}.tar.gz

build:
  number: 1
  skip: not win64

requirements:
  build:
    - if: win64
      then: vs2017_win-64
    - cmake
    - ninja
  host:
    - azure-c-shared-utility
  run:
    - azure-c-shared-utility
  run_exports:
    - ${{ pin_subpackage(name, exact=True) }}

tests:
  - script:
      - if: win
        then: if not exist %PREFIX%\\Library\\bin\\uamqp.dll exit 1

about:
  license: MIT
  license_file: LICENSE
  summary: |
    uAMQP is a general purpose C library for AMQP 1.0.


  homepage: https://github.com/Azure/azure-uamqp-c

extra:
  recipe-maintainers:
    - xylar
    - seanyen
